### ISSUE TITLE
Create standup notes template

### ISSUE THREAD

**Issue by mustaqs** [mustaqs/fa22-cse110-lab3#1]
# Issue Report Lab 3
- [ ] Create a standup notes template in a Markdown file standup.md

## Tasks
- [ ] Read [https://www.atlassian.com/agile/scrum/standups](Agile Standup Info) 
- [ ] Create a template to use for standup meetings for future standups
## Process
- [ ] Section for intro to meeting
- [ ] Section for each team member info/notes
- [ ] Section for roadblocks
- [ ] Section for followups
- [ ] Noteworthy takeaways
## Testing
N/A
